# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Doodling Dev Blog'
tagline:          'Draw. Code. Draw about code.'
description:      ''
url:              https://doodlingdev.com
baseurl:          /

author:
  name:           'Aji Slater'
  url:            https://twitter.com/doodlingdev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/doodlingdev/doodlingdev.github.io

plugins:          [jekyll-paginate]
